[package]
name = "sas-reader-2000"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
byteorder = "1.4"
csv = "1.1"
chrono = "0.4.38"
streaming-iterator = "0.1.9"
derive_builder = "0.20.1"
polars = { version = "0.43.1", features = ["lazy"] }
